### ISSUE TITLE
Threshold duration before notification

### ISSUE THREAD

**Issue by franciscolourenco** [fisherman/done#18]
I've been thinking about reducing the default minimum period a command needs to run in order to trigger a notification from `10s` to `3s` or `5s`. Any scenarios where you think this would be undesirable?

**Comment by dawehner** [comment]
Works for me. My commands are mostly instant or long

**Comment by dawehner** [comment]
We should find out the average focus time of us using stats and set the time automatically ;(

**Comment by aristidesfl** [comment]
The question is: if you switch away from the terminal to another app right after starting a command, and it finishes after 4s, would you not want to know about it? The notification never gets triggered as long as you are looking at the output of the command.

**Comment by dawehner** [comment]
Maybe it would be nice if the user didn't came back to the shell in a
certain time. That's harder of course than just changing this time.

On Tue, 14 Feb 2017, 01:07 Francisco Lourenço, <notifications@github.com>
wrote:

The question is: if you switch away from the terminal to another app right
after starting a command, and it finishes after 4s, would you not want to
know about it? The notification never gets triggered as long as you are
looking at the output of the command.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/fisherman/done/issues/18#issuecomment-279575255>, or mute
the thread
